# Módulo 07, Tarefa 01

Vamos começar a mexer na nossa base de projeto? Já fizemos um exercício de montar a variável resposta, já pudemos perceber que essa atividade pode não ser trivial. Vamos agora trabalhar a base para que fique propícia ao *scikitlearn* para trabalharmos.

Lembrando, a base se chama demo01.csv, e originalmente está publicada [aqui](https://www.kaggle.com/rikdifos/credit-card-approval-prediction).

#### 1) Carregue a base e avalie:

- As variáveis
- Tipos de dados de cada variável
- Quantidade de missings
- Distribuição da variável resposta (mau)

In [72]:
import pandas as pd


In [73]:
# Carregar a base de dados
df = pd.read_csv('demo01.csv')


In [74]:
# Avaliar as variáveis
print(df.columns)


Index(['sexo', 'posse_de_veiculo', 'posse_de_imovel', 'qtd_filhos',
       'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia', 'idade',
       'tempo_emprego', 'possui_celular', 'possui_fone_comercial',
       'possui_fone', 'possui_email', 'qt_pessoas_residencia', 'mau'],
      dtype='object')


In [32]:
# Avaliar os tipos de dados de cada variável
print(df.dtypes)


sexo                      object
posse_de_veiculo          object
posse_de_imovel           object
qtd_filhos                 int64
tipo_renda                object
educacao                  object
estado_civil              object
tipo_residencia           object
idade                    float64
tempo_emprego            float64
possui_celular             int64
possui_fone_comercial      int64
possui_fone                int64
possui_email               int64
qt_pessoas_residencia    float64
mau                         bool
dtype: object


In [33]:
# Quantidade de valores ausentes (missings)
print(df.isnull().sum())


sexo                     0
posse_de_veiculo         0
posse_de_imovel          0
qtd_filhos               0
tipo_renda               0
educacao                 0
estado_civil             0
tipo_residencia          0
idade                    0
tempo_emprego            0
possui_celular           0
possui_fone_comercial    0
possui_fone              0
possui_email             0
qt_pessoas_residencia    0
mau                      0
dtype: int64


In [34]:
# Distribuição da variável resposta (mau)
print(df['mau'].value_counts())

False    16260
True       390
Name: mau, dtype: int64


#### 2) Vamos montar um metadados

1. Crie um dataframe com os nomes de cada variável e o tipo de dados de cada variável.
2. Adicione uma coluna nesse *dataframe* chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável.
    Dica:
        1. inicie uma lista vazia
        2. faça um for ao longo dos nomes das variáveis,
        3. conte o número de categorias dessa variável
        4. acumule essa informação de 3. na lista que você criou em 1.
        5. No final, essa lista pode ser atribuída à nossa variável.
3. Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}.

##### 2.1. DataFrame para o metadados:

In [35]:
metadata = pd.DataFrame({'variavel': df.columns, 'tipo': df.dtypes})
metadata

variavel     tipo
sexo                                    sexo   object
posse_de_veiculo            posse_de_veiculo   object
posse_de_imovel              posse_de_imovel   object
qtd_filhos                        qtd_filhos    int64
tipo_renda                        tipo_renda   object
educacao                            educacao   object
estado_civil                    estado_civil   object
tipo_residencia              tipo_residencia   object
idade                                  idade  float64
tempo_emprego                  tempo_emprego  float64
possui_celular                possui_celular    int64
possui_fone_comercial  possui_fone_comercial    int64
possui_fone                      possui_fone    int64
possui_email                    possui_email    int64
qt_pessoas_residencia  qt_pessoas_residencia  float64
mau                                      mau     bool

##### 2.2. Adicionar uma coluna nesse *dataframe* chamada "qtd_categorias" e colocar o número de categorias correspondente de cada variável:

In [36]:
# Calcular a quantidade de categorias para cada variável
qtd_categorias = []
for var in df.columns:
    qtd_categorias.append(df[var].nunique())

# Adicionar a quantidade de categorias ao metadados
metadata['qtd_categorias'] = qtd_categorias

In [37]:
metadata

variavel     tipo  qtd_categorias
sexo                                    sexo   object               2
posse_de_veiculo            posse_de_veiculo   object               2
posse_de_imovel              posse_de_imovel   object               2
qtd_filhos                        qtd_filhos    int64               8
tipo_renda                        tipo_renda   object               5
educacao                            educacao   object               5
estado_civil                    estado_civil   object               5
tipo_residencia              tipo_residencia   object               6
idade                                  idade  float64            5298
tempo_emprego                  tempo_emprego  float64            3005
possui_celular                possui_celular    int64               1
possui_fone_comercial  possui_fone_comercial    int64               2
possui_fone                      possui_fone    int64               2
possui_email                    possui_email    int64               2
qt_pessoas_residencia  qt_pessoas_residencia  float64               9
mau                                      mau     bool               2

##### 2.3. Criar variáveis dummy para as variáveis necessárias:

In [47]:
# Criar variáveis dummy para as variáveis categóricas
for var in df.columns:
    if df[var].dtype == 'object':
        dummies = pd.get_dummies(df[var], prefix=var)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(var, axis=1)
df.columns

Index(['qtd_filhos', 'idade', 'tempo_emprego', 'possui_celular',
       'possui_fone_comercial', 'possui_fone', 'possui_email',
       'qt_pessoas_residencia', 'mau', 'sexo_F', 'sexo_M',
       'posse_de_veiculo_N', 'posse_de_veiculo_Y', 'posse_de_imovel_N',
       'posse_de_imovel_Y', 'tipo_renda_Commercial associate',
       'tipo_renda_Pensioner', 'tipo_renda_State servant',
       'tipo_renda_Student', 'tipo_renda_Working', 'educacao_Academic degree',
       'educacao_Higher education', 'educacao_Incomplete higher',
       'educacao_Lower secondary', 'educacao_Secondary / secondary special',
       'estado_civil_Civil marriage', 'estado_civil_Married',
       'estado_civil_Separated', 'estado_civil_Single / not married',
       'estado_civil_Widow', 'tipo_residencia_Co-op apartment',
       'tipo_residencia_House / apartment',
       'tipo_residencia_Municipal apartment',
       'tipo_residencia_Office apartment', 'tipo_residencia_Rented apartment',
       'tipo_residencia_With par

#### 3) Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}. Crie um *dataframe* apenas com as variáveis apropriadas para entrada no scikitlearn - elimine as variáveis tipo *str*, mantendo apenas suas versões *dummy*.

In [39]:
# Criar um novo DataFrame para armazenar as variáveis numéricas e dummy
df_novo = pd.DataFrame()

# Para cada variável no DataFrame original:
for var in df.columns:
    # Se a variável é numérica ou booleana, copie-a para o novo DataFrame:
    if df[var].dtype in ['int64', 'float64', 'bool']:
        df_novo[var] = df[var]
    # Se a variável é categórica;
    elif df[var].dtype == 'object':
        # Cria variáveis dummy para essa variável:
        dummies = pd.get_dummies(df[var], prefix=var)
        # Adiciona as variáveis dummy ao novo DataFrame:
        df_novo = pd.concat([df_novo, dummies], axis=1)

df_novo

qtd_filhos      idade  tempo_emprego  possui_celular  \
0               0  58.832877       3.106849               1   
1               0  52.356164       8.358904               1   
2               0  52.356164       8.358904               1   
3               0  46.224658       2.106849               1   
4               0  29.230137       3.021918               1   
...           ...        ...            ...             ...   
16645           0  54.109589       9.884932               1   
16646           0  43.389041       7.380822               1   
16647           0  30.005479       9.800000               1   
16648           0  30.005479       9.800000               1   
16649           0  33.936986       3.630137               1   

       possui_fone_comercial  possui_fone  possui_email  \
0                          0            0             0   
1                          0            1             1   
2                          0            1             1   
3                          1            1             1   
4                          0            0             0   
...                      ...          ...           ...   
16645                      0            0             0   
16646                      1            1             0   
16647                      1            0             0   
16648                      1            0             0   
16649                      0            1             1   

       qt_pessoas_residencia    mau  
0                        2.0  False  
1                        1.0  False  
2                        1.0  False  
3                        2.0  False  
4                        2.0  False  
...                      ...    ...  
16645                    2.0   True  
16646                    2.0   True  
16647                    2.0   True  
16648                    2.0   True  
16649                    2.0   True  

[16650 rows x 9 columns]

#### 4) Qual variável é mais poderosa?

Considere as variáveis ```possui_email``` e ```posse_de_veiculo```. Faça uma tabela cruzada entre elas e responda qual delas te parece mais poderosa para prever a probabilidade de ```mau = 1```?

In [62]:
# Criar tabelas de contingência:
contingencia_email = pd.crosstab(df['mau'], df['possui_email'])
contingencia_veiculo = pd.crosstab(df['mau'], df['posse_de_veiculo'])


In [63]:
print("Tabela de contingência para 'possui_email':")
contingencia_email

Tabela de contingência para 'possui_email':


possui_email      0     1
mau                      
False         14810  1450
True            360    30

In [64]:
print("Tabela de contingência para 'posse_de_veiculo':")
contingencia_veiculo

Tabela de contingência para 'posse_de_veiculo':


posse_de_veiculo     N     Y
mau                         
False             9931  6329
True               247   143

Cada tabela mostra a distribuição da variável resposta mau para cada categoria das variáveis.

Para determinar qual variável é mais poderosa, é necessário analisar a  distribuição da variável resposta em cada categoria das variáveis preditoras. A variável que mostra a maior diferença na distribuição da variável resposta entre suas categorias pode ser considerada mais poderosa.



> Para a variável possui_email:

Dos clientes que não possuem e-mail (0), 360 são mau = True e 14.810 são mau = False.

Dos clientes que possuem e-mail (1), 30 são mau = True e 1.450 são mau = False.





> Para a variável posse_de_veiculo:

Dos clientes que não possuem veículo (N), 247 são mau = True e 9.931 são mau = False.

Dos clientes que possuem veículo (Y), 143 são mau = True e 6.329 são mau = False.



###### Agora, calculando a taxa de mau = True para cada categoria:


In [66]:
# Taxa de mau = True para clientes sem e-mail:
360 / (360 + 14810)

0.023731048121292023

In [69]:
# Taxa de mau = True para clientes com e-mail:
30 / (30 + 1450)

0.02027027027027027

In [70]:
#Taxa de mau = True para clientes sem veículo:
247 / (247 + 9931)

0.02426802908233445

In [71]:
# Taxa de mau = True para clientes com veículo:
143 / (143 + 6329)

0.022095179233621757



Observando essas taxas, nota-se que a variável possui_email mostra uma diferença maior na taxa de mau = True entre suas categorias em comparação com a variável posse_de_veiculo.
Portanto, com base nesses dados, pode-se dizer que a variável possui_email parece ser mais poderosa para prever a probabilidade de mau = True.

#### 5) Salve a base, pois ela será utilizada no final deste módulo.

In [75]:
df.to_csv('demo01_transformado.csv', index=False)